# This is used to generate istio.yaml for minimal, demo mode.
# It is shipped with the release, used for bookinfo or quick installation of istio.
# Includes components used in the demo, defaults to alpha3 rules.

# If running in minikube you may add:
# --set global.nodePort=true
# --set ingressgateway.service.type=NodePort
global:
  nodePort: false

ingress:
  # Ingress is used for migration, for alpha3 we expect ingressgateway
  enabled: false

prometheus:
  enabled: true

pilot:
  traceSampling: 100.0

sidecarInjectorWebhook:
  enabled: true
  enableNamespacesByDefault: false

grafana:
  enabled: true

tracing:
  enabled: true

servicegraph:
  enabled: true

galley:
  enabled: true
