# This is used to generate istio-auth.yaml for minimal, demo mode with MTLS enabled.
# It is shipped with the release, used for bookinfo or quick installation of istio.
# Includes components used in the demo, defaults to alpha3 rules.
global:
  controlPlaneSecurityEnabled: true

  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: true

ingress:
  # Ingress is used for migration, for alpha3 we expect ingressgateway
  enabled: false

prometheus:
  enabled: true

pilot:
  traceSampling: 100.0

sidecarInjectorWebhook:
  enabled: true
  enableNamespacesByDefault: false

grafana:
  enabled: true

tracing:
  enabled: true

servicegraph:
  enabled: true

galley:
  enabled: true
